server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: spring-mvc
  security:
    user:
      password: user
      name: user
      roles: ADMIN
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    client-id: spring-mvc
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      batch-size: 50
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      kv:
        enabled: false
      enabled: false

management:
#  observations:
#    key-values:
#      cluster: dev
#    enable:
#      spring:
#        security: false
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans
  server:
    port: 8090
logging:
#  pattern:
#    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: true