server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: test1
  security:
    user:
      password: user
      name: user
      roles: ADMIN
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    client-id: test1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      batch-size: 50
  jpa:
    hibernate:
      ddl-auto: update

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{X-CORRELATION-ID:-}]"