spring:
  application:
    name: spring-mvc-secret
  security:
    user:
      password: admin
      name: admin
  kafka:
    bootstrap-servers: broker:29092
management:
  endpoint:
    health:
      show-details: never

truststore:
  path: file:/services/vault/certs.jks
  password: 12345
