scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: [ 'service-native:8090' ]
        labels:
          application: 'Native Spring MVC'
      - targets: [ 'service-java:8090' ]
        labels:
          application: 'Spring MVC'
      - targets: [ 'service-java-reactive:8090' ]
        labels:
          application: 'Native Spring Webflux'
      - targets: [ 'service-native-reactive:8090' ]
        labels:
          application: 'Spring Webflux'